// AUTH
export const AUTH_START = 'AUTH_START'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_RESET = 'AUTH_RESET'


// User Book List
export const USERLIST_ACTION_START = 'USERLIST_ACTION_START'
export const USERLIST_ACTION_FAIL = 'USERLIST_ACTION_FAIL'
export const USERLIST_ACTION_SUCCESS = 'FETCH_USERLIST_SUCCESS'
export const USERLIST_SET_FILTER = 'USERLIST_SET_FILTER'
export const SET_SELECTED_BOOK = 'SET_SELECTED_BOOK'
export const RESET_SELECTED_BOOK = 'RESET_SELECTED_BOOK'

